const spanish1UnitIWordList = [
    { word: "¿qué deporte juegas tú?", hint: "What sport do you play?" },
    { word: "juego", hint: "I play" },
    { word: "practico", hint: "I practice" },
    { word: "¿cómo juegas?", hint: "How do you play?" },
    { word: "¿sabes jugar?", hint: "Do you know how to play?" },
    { word: "sé", hint: "I know" },
    { word: "no sé", hint: "I don't know" },
    { word: "¿qué necesitas para jugar?", hint: "What do you need to play?" },
    { word: "necesitas", hint: "You need" },
    { word: "fútbol americano", hint: "football" },
    { word: "fútbol", hint: "soccer" },
    { word: "porrista", hint: "cheerleading" },
    { word: "basquétbol", hint: "basketball" },
    { word: "baloncesto", hint: "basketball (Spain)"},
    { word: "equipo de baile", hint: "dance team" },
    { word: "boliche", hint: "bowling" },
    { word: "tenis", hint: "tennis" },
    { word: "béisbol", hint: "baseball" },
    { word: "lucha libre", hint: "wrestling" },
    { word: "golf", hint: "Golf" },
    { word: "atletismo", hint: "track and field" },
    { word: "natación", hint: "swimming" },
    { word: "levantamiento de pesas", hint: "weightlifting" },
    { word: "carreras de autos", hint: "car racing" },
    { word: "correr a larga distancia", hint: "long distance running" },
    { word: "softbol", hint: "softball" },
    { word: "voleibol", hint: "volleyball" },
    { word: "ganar", hint: "to win" },
    { word: "patear", hint: "to kick" },
    { word: "el balón", hint: "the ball (inflateable)"},
    { word: "empezar", hint: "to begin" },
    { word: "perder", hint: "to lose" },
    { word: "meter un gol", hint: "to score a goal" },
    { word: "nadar", hint: "to swim" },
    { word: "la piscina", hint: "swimming pool" },
    { word: "saltar", hint: "to jump" },
    { word: "marcar puntos", hint: "to score points" },
    { word: "levantar las pesas", hint: "To lift weights" },
    { word: "tirar la pelota", hint: "To throw the ball" },
    { word: "pegar", hint: "to hit" },
    { word: "llevar", hint: "to wear" },
    { word: "el uniforme", hint: "uniform" },
    { word: "la máscara", hint: "mask" },
    { word: "atrapar", hint: "to catch" },
    { word: "el guante", hint: "glove" },
    { word: "parar", hint: "to stop" },
    { word: "batear", hint: "to bat" },
    { word: "el bate", hint: "baseball bat" },
    { word: "juegas", hint: "you play" },
    { word: "juega", hint: "he/she plays" },
    { word: "jugamos", hint: "we play" },
    { word: "juegan", hint: "they play" }
];
