const spanish1UnitGWordList = [
    { word: "¿cuántos años tienes?", hint: "How old are you?" },
    { word: "¿cuántos años tiene?", hint: "How old is he/she/it?" },
    { word: "tengo años", hint: "I am_____old" },
    { word: "mi guitarra", hint: "my guitar" },
    { word: "mis guitarras", hint: "my guitars" },
    { word: "tu libro", hint: "Your book" },
    { word: "tus libros", hint: "Your books" },
    { word: "su perro", hint: "His/her/their dog" },
    { word: "sus perros", hint: "His/her/their dogs" },
    { word: "madre", hint: "mother" },
    { word: "mamá", hint: "mom" },
    { word: "padre", hint: "father" },
    { word: "papá", hint: "dad" },
    { word: "hermano", hint: "brother" },
    { word: "hermana", hint: "sister" },
    { word: "hermanastro", hint: "step brother" },
    { word: "hermanastra", hint: "step sister" },
    { word: "tío", hint: "uncle" },
    { word: "tía", hint: "aunt" },
    { word: "abuelo", hint: "grandpa" },
    { word: "abuela", hint: "grandma" },
    { word: "primo", hint: "boy cousin" },
    { word: "prima", hint: "girl cousin" },
    { word: "mascota", hint: "pet" },
    { word: "perro", hint: "dog" },
    { word: "gato", hint: "cat" },
    { word: "novio", hint: "boyfriend" },
    { word: "novia", hint: "girlfriend" },
    { word: "hijo", hint: "son" }, 
    { word: "hija", hint: "daughter" },
    { word: "niño", hint: "boy child"},
    { word: "niña", hint: "girl child" },
    { word: "grande", hint: "big" },
    { word: "pequeño", hint: "small" },
    { word: "simpático", hint: "nice" },
    { word: "antipático", hint: "mean" },
    { word: "amable", hint: "kind" },
    { word: "cómico", hint: "funny" },
    { word: "atractivo", hint: "attractive" },
    { word: "bonito", hint: "pretty" },
    { word: "guapo", hint: "handsome/good looking" },
    { word: "divertido", hint: "fun" },
    { word: "trabajador", hint: "hard working" },
    { word: "trabajadora", hint: "hard working woman" },
    { word: "cariñoso", hint: "affectionate" },
    { word: "mayor", hint: "older" },
    { word: "menor", hint: "younger" },
    { word: "bebé", hint: "baby" },
    { word: "sociable", hint: "outgoing" },
    { word: "tímido", hint: "shy" },
    { word: "gordo", hint: "overweight" },
    { word: "flaco", hint: "skinny" },
    { word: "más que", hint: "more than" },
    { word: "menos que", hint: "less than" },
    { word: "tan como que", hint: "as" },
    { word: "mejor", hint: "better" },
    { word: "peor", hint: "worse" },
    { word: "trabajar", hint: "to work" },
    { word: "ir de vacaciones", hint: "to go on vacation" },
    { word: "nos llevamos bien", hint: "we get along well" },
    { word: "cocinar", hint: "to cook" },
    { word: "cuidar", hint: "to take care of" },
    { word: "limpiar", hint: "to clean" },
    { word: "se llevan mal", hint: "they don't get along" }
];
