const spanishNumbers100 = [
        { hint: "one", word: "uno" },
        { hint: "two", word: "dos" },
        { hint: "three", word: "tres" },
        { hint: "four", word: "cuatro" },
        { hint: "five", word: "cinco" },
        { hint: "six", word: "seis" },
        { hint: "seven", word: "siete" },
        { hint: "eight", word: "ocho" },
        { hint: "nine", word: "nueve" },
        { hint: "ten", word: "diez" },
        { hint: "11", word: "once" },
        { hint: "12", word: "doce" },
        { hint: "13", word: "trece" },
        { hint: "14", word: "catorce" },
        { hint: "15", word: "quince" },
        { hint: "16", word: "dieciséis" },
        { hint: "17", word: "diecisiete" },
        { hint: "19", word: "diecinueve" },
        { hint: "20", word: "veinte" },
        { hint: "21", word: "veintiuno" },
        { hint: "22", word: "veintidós" },
        { hint: "23", word: "veintitrés" },
        { hint: "24", word: "veinticuatro" },
        { hint: "25", word: "veinticinco" },
        { hint: "26", word: "veintiséis" },
        { hint: "27", word: "veintisiete" },
        { hint: "28", word: "veintiocho" },
        { hint: "29", word: "veintinueve" },
        { hint: "30", word: "treinta" },
        { hint: "31", word: "treinta y uno" },
        { hint: "32", word: "treinta y dos" },
        { hint: "33", word: "treinta y tres" },
        { hint: "34", word: "treinta y cuatro" },
        { hint: "35", word: "treinta y cinco" },
        { hint: "36", word: "treinta y seis" },
        { hint: "37", word: "treinta y siete" },
        { hint: "38", word: "treinta y ocho" },
        { hint: "39", word: "treinta y nueve" },
        { hint: "40", word: "cuarenta" },
        { hint: "41", word: "cuarenta y uno" },
        { hint: "42", word: "cuarenta y dos" },
        { hint: "43", word: "cuarenta y tres" },
        { hint: "44", word: "cuarenta y cuatro" },
        { hint: "45", word: "cuarenta y cinco" },
        { hint: "46", word: "cuarenta y seis" },
        { hint: "47", word: "cuarenta y siete" },
        { hint: "48", word: "cuarenta y ocho" },
        { hint: "49", word: "cuarenta y nueve" },
        { hint: "50", word: "cincuenta" },
        { hint: "51", word: "cincuenta y uno" },
        { hint: "52", word: "cincuenta y dos" },
        { hint: "53", word: "cincuenta y tres" },
        { hint: "54", word: "cincuenta y cuatro" },
        { hint: "55", word: "cincuenta y cinco" },
        { hint: "56", word: "cincuenta y seis" },
        { hint: "57", word: "cincuenta y siete" },
        { hint: "58", word: "cincuenta y ocho" },
        { hint: "59", word: "cincuenta y nueve" },
        { hint: "60", word: "sesenta" },
        { hint: "61", word: "sesenta y uno" },
        { hint: "62", word: "sesenta y dos" },
        { hint: "63", word: "sesenta y tres" },
        { hint: "64", word: "sesenta y cuatro" },
        { hint: "65", word: "sesenta y cinco" },
        { hint: "66", word: "sesenta y seis" },
        { hint: "67", word: "sesenta y siete" },
        { hint: "68", word: "sesenta y ocho" },
        { hint: "69", word: "sesenta y nueve" },
        { hint: "70", word: "setenta" },
        { hint: "71", word: "setenta y uno" },
        { hint: "72", word: "setenta y dos" },
        { hint: "73", word: "setenta y tres" },
        { hint: "74", word: "setenta y cuatro" },
        { hint: "75", word: "setenta y cinco" },
        { hint: "76", word: "setenta y seis" },
        { hint: "77", word: "setenta y siete" },
        { hint: "78", word: "setenta y ocho" },
        { hint: "79", word: "setenta y nueve" },
        { hint: "80", word: "ochenta" },
        { hint: "81", word: "ochenta y uno" },
        { hint: "82", word: "ochenta y dos" },
        { hint: "83", word: "ochenta y tres" },
        { hint: "84", word: "ochenta y cuatro" },
        { hint: "85", word: "ochenta y cinco" },
        { hint: "86", word: "ochenta y seis" },
        { hint: "87", word: "ochenta y siete" },
        { hint: "88", word: "ochenta y ocho" },
        { hint: "89", word: "ochenta y nueve" },
        { hint: "90", word: "noventa" },
        { hint: "91", word: "noventa y uno" },
        { hint: "92", word: "noventa y dos" },
        { hint: "93", word: "noventa y tres" },
        { hint: "94", word: "noventa y cuatro" },
        { hint: "95", word: "noventa y cinco" },
        { hint: "96", word: "noventa y seis" },
        { hint: "97", word: "noventa y siete" },
        { hint: "98", word: "noventa y ocho" },
        { hint: "99", word: "noventa y nueve" },
        { hint: "100", word: "cien" },
        { hint: "101", word: "ciento uno" }
    ];