const spanish1UnitAWordList = [
    { word: "¿cómo?", hint: "How" },
    { word: "¿cómo estás?", hint: "How are you?" },
    { word: "¿cómo se llama?", hint: "What is his/her name?" },
    { word: "¿qué?", hint: "What?" },
    { word: "¿qué dice?", hint: "What does ________ say?" },
    { word: "¿dónde?", hint: "Where?" },
    { word: "¿cuál?", hint: "Which (or what)" },
    { word: "¿cuál es tu número de teléfono?", hint: "What is your phone number?" },
    { word: "¿cuál es tu correo electrónico?", hint: "What is your email?" },
    { word: "cero", hint: "zero" },
    { word: "uno", hint: "one" },
    { word: "dos", hint: "two" },
    { word: "tres", hint: "three" },
    { word: "cuatro", hint: "four" },
    { word: "cinco", hint: "five" },
    { word: "seis", hint: "six" },
    { word: "siete", hint: "seven" },
    { word: "ocho", hint: "eight" },
    { word: "nueve", hint: "nine" },
    { word: "diez", hint: "ten" },
    { word: "once", hint: "eleven" },
    { word: "doce", hint: "twelve" },
    { word: "trece", hint: "thirteen" },
    { word: "catorce", hint: "fourteen" },
    { word: "quince", hint: "fifteen" },
    { word: "dieciséis", hint: "sixteen" },
    { word: "diecisiete", hint: "seventeen" },
    { word: "dieciocho", hint: "eighteen" },
    { word: "diecinueve", hint: "nineteen" },
    { word: "veinte", hint: "twenty" },
    { word: "veintiuno", hint: "twenty-one" },
    { word: "veintidós", hint: "twenty-two" },
    { word: "veintitrés", hint: "twenty-three" },
    { word: "veinticuatro", hint: "twenty-four" },
    { word: "veinticinco", hint: "twenty-five" },
    { word: "veintiséis", hint: "twenty-six" },
    { word: "veintisiete", hint: "twenty-seven" },
    { word: "veintiocho", hint: "twenty-eight" },
    { word: "veintinueve", hint: "twenty-nine" },
    { word: "treinta", hint: "thirty" },
    { word: "roberto es un estudiante nuevo.", hint: "Roberto is a new student." },
    { word: "roberto va a la escuela nueva.", hint: "Roberto goes to the new school." },
    { word: "nuevo", hint: "new" },
    { word: "estudiante", hint: "student" },
    { word: "la escuela", hint: "school" },
    { word: "roberto va a la oficina.", hint: "Roberto goes to the office" },
    { word: "va", hint: "he goes" },
    { word: "la oficina", hint: "office" },
    { word: "la secretaria de la oficina dice:", hint: "The office secretary says:" },
    { word: "la secretaria", hint: "secretary" },
    { word: "la oficina", hint: "office" },
    { word: "roberto está frustrado.", hint: "Roberto is frustrated" },
    { word: "está", hint: "he is" },
    { word: "frustrado", hint: "frustrated" },
    { word: "mi nombre es Roberto.", hint: "My name is Roberto" },
    { word: "el nombre", hint: "name" },
    { word: "el director va a la oficina.", hint: "The principal goes to the office." },
    { word: "el director", hint: "the principal" },
    { word: "¿de dónde eres, Roberto?", hint: "Where are you from, Roberto?" },
    { word: "¿de dónde eres?", hint: "¿Where are you from?" },
    { word: "soy de", hint: "I am from" },
    { word: "muy bien", hint: "Very good." },
    { word: "roberto no está contento.", hint: "Roberto is not pleased." },
    { word: "contento", hint: "content / pleased" },
    { word: "roberto va al salón de clases", hint: "Roberto goes to the classroom" },
    { word: "el salón", hint: "Room" },
    { word: "el salón de clases", hint: "classroom" },
    { word: "roberto ve a una compañera", hint: "Roberto sees a classmate." },
    { word: "ve", hint: "He sees" },
    { word: "una compañera", hint: "a classmate" },
    { word: "yo soy estudiante nuevo.", hint: "I am a new student." },
    { word: "yo soy", hint: "I am" },
    { word: "roberto y sandra son amigos.", hint: "Roberto y Sandra are friends." },
    { word: "el amigo", hint: "friend" },
    { word: "los saludos", hint: "Greetings" },
    { word: "hola", hint: "Hello" },
    { word: "¿qué tal", hint: "what's up?" },
    { word: "buenos días", hint: "Good morning" },
    { word: "buenas tardes", hint: "Good afternoon" },
    { word: "¿cómo te llamas?", hint: "¿What's your name?" },
    { word: "me llamo", hint: "My name is" },
    { word: "¿cómo se escribe?", hint: "How do you spell?" },
    { word: "se escribe", hint: "It is spelled" },
    { word: "nice to meet you!", hint: "¡Mucho gusto!" },
]