const spanish1UnitDWordList = [
    { hint: "jumps", word: "salta" },
    { hint: "walks", word: "camina" },
    { hint: "spits", word: "escupe" },
    { hint: "blowdart", word: "cerbatana" },
    { hint: "rainforest", word: "la selva" },
    { hint: "the country Carlos lives in", word: "ecuador" },
    { hint: "South America", word: "sudamérica" },
    { hint: "lake", word: "el lago" },
    { hint: "amable", word: "the opposite of cruel" },
    { hint: "leader", word: "el lider" },
    { hint: "large turtle", word: "la tortuga grande" },
    { hint: "explodes", word: "explota" },
    { hint: "tree", word: "arbol" },
    { hint: "crashes", word: "choca" },
    { hint: "suddenly", word: "de repente" },
    { hint: "then", word: "entonces" },
    { hint: "and", word: "y" },
    { hint: "says", word: "dice" },
    { hint: "with", word: "con" },
    { hint: "boat", word: "bote" },
    { hint: "shark", word: "tiburón" },
    { hint: "destroys", word: "destruye" },
    { hint: "la rata super grande", word: "capibara" },
    { hint: "webbed", word: "palmeadas" },
    { hint: "feet", word: "patas" },
    { hint: "farts", word: "tiene gases" },
    { hint: "has", word: "tiene" },
    { hint: "is", word: "es" },
    { hint: "to swim", word: "nadar" },
    { hint: "well", word: "bien" },
    { hint: "good", word: "bueno" },
    { hint: "bad", word: "malo" },
    { hint: "monkey", word: "el mono" },
    { hint: "can't", word: "no puede" },
    { hint: "the opposite of feliz", word: "furioso" },
    { hint: "happy", word: "feliz" },
    { hint: "enters", word: "entra" },
    { hint: "quickly", word: "rápido" },
    { hint: "wants", word: "quiere" },
    { hint: "friend", word: "amigo" },
    { hint: "water", word: "agua" },
    { hint: "on top of", word: "encima" },
    { hint: "head", word: "cabeza" },
    { hint: "runs", word: "corre" },
    { hint: "the capital of Ecuador", word: "quito" },
    { hint: "seeds", word: "semillas" },
    { hint: "serpiente", word: "anaconda" }
  ];
  