const spanish1UnitBWordList = [
    { word: "mirar Netflix", hint: "to watch Netflix" },
    { word: "jugar fútbol", hint: "to play soccer" },
    { word: "jugar basquetbol", hint: "to play basketball" },
    { word: "nadar", hint: "to swim" },
    { word: "hacer la tarea", hint: "to do homework" },
    { word: "comer", hint: "to eat" },
    { word: "jugar videojuegos", hint: "to play videogames" },
    { word: "textear", hint: "to text" },
    { word: "leer un libro", hint: "to read a book" },
    { word: "escuchar música", hint: "to listen to music" },
    { word: "ir al cine", hint: "to go to movies" },
    { word: "ir de compras", hint: "to go shopping" },
    { word: "correr", hint: "to run" },
    { word: "jugar beisbol", hint: "to play baseball" },
    { word: "dormir", hint: "to sleep" },
    { word: "el tiempo", hint: "the weather" },
    { word: "hace frío", hint: "It's cold" },
    { word: "hace calor", hint: "It's hot" },
    { word: "hace sol", hint: "It's sunny" },
    { word: "está nublado", hint: "It's cloudy" },
    { word: "hace viento", hint: "It's windy" },
    { word: "llueve", hint: "It's raining" },
    { word: "nieva", hint: "It's snowing" },
    { word: "¿qué día es hoy?", hint: "What day is today?" },
    { word: "hoy es martes.", hint: "Today is Tuesday." },
    { word: "¿cuál es la fecha?", hint: "What is today's date?" },
    { word: "hoy es el treinta de agosto.", hint: "Today is the 30th of August." },
    { word: "¿cómo se escribe tu nombre?", hint: "How is your name written/spelled?" },
    { word: "mi nombre se escribe", hint: "My name is spelled" },
    { word: "¿cuál es tu número de teléfono?", hint: "What is your phone number?" },
    { word: "mi número de teléfono es", hint: "My phone number is" },
    { word: "¿cuántas estaciones hay?", hint: "How many seasons are there?" },
    { word: "¿qué son los meses del verano?", hint: "What are the months of Summer?" },
    { word: "¿qué son los días de la semana?", hint: "What are the days of the week?" },
    { word: "¿qué son los meses del año?", hint: "What are the months of the year?" },
    { word: "¿qué te gusta hacer?", hint: "What do you like to do?" },
    { word: "¿dé dónde eres?", hint: "Where are you from?" },
    { word: "¿cómo te llamas?", hint: "What is your name?" },
    { word: "¿cómo se llama?", hint: "What is his/her name?" },
    { word: "me llamo", hint: "My name is..." },
    { word: "se llama", hint: "His/her name is..." },
    { word: "soy de", hint: "I'm from..." },
    { word: "¿qué tiempo hace?", hint: "What's the weather like?" },
    { word: "¿cuándo es tu cumpleaños?", hint: "When is your birthday?" },
    { word: "enero", hint: "January" },
    { word: "febrero", hint: "February" },
    { word: "marzo", hint: "March" },
    { word: "abril", hint: "April" },
    { word: "mayo", hint: "May" },
    { word: "junio", hint: "June" },
    { word: "julio", hint: "July" },
    { word: "agosto", hint: "August" },
    { word: "septiembre", hint: "September" },
    { word: "octubre", hint: "October" },
    { word: "noviembre", hint: "November" },
    { word: "diciembre", hint: "December" },
    { word: "lunes", hint: "Monday" },
    { word: "martes", hint: "Tuesday" },
    { word: "miércoles", hint: "Wednesday" },
    { word: "jueves", hint: "Thursday" },
    { word: "viernes", hint: "Friday" },
    { word: "sábado", hint: "Saturday" },
    { word: "domingo", hint: "Sunday" },
    { word: "verano", hint: "summer" },
    { word: "invierno", hint: "winter" },
    { word: "otoño", hint: "fall, autumn" },
    { word: "primavera", hint: "spring" },
    { word: "hoy", hint: "today" },
    { word: "hoy es el día de mes", hint: "Today is the (day) of (month)." },
    { word: "mañana", hint: "tomorrow" },
    { word: "primero", hint: "the first (of the month)" },
    { word: "es el tres de noviembre.", hint: "It's November 3rd." },
    { word: "es el primero de enero.", hint: "It's January 1st." },
    { word: "la fecha", hint: "date" },
    { word: "el mes", hint: "month" },
    { word: "la estación", hint: "season" },
    { word: "el año", hint: "year" },
    { word: "el día", hint: "day" },
    { word: "la semana", hint: "week" },
    { word: "el fin de semana", hint: "weekend" },
    { word: "me gusta", hint: "I like" },
    { word: "no me gusta", hint: "I don't like" },
    { word: "¿te gusta?", hint: "Do you like?" },
    { word: "me gusta mucho", hint: "I like a lot" },
    { word: "¿qué te gusta?", hint: "What do you like?" },
    { word: "la pizza", hint: "Pizza" },
    { word: "las papas fritas", hint: "French Fries" },
    { word: "la hamburguesa", hint: "Hamburger" },
    { word: "el chocolate", hint: "Chocolate" },
    { word: "las verduras", hint: "Vegetables" },
    { word: "los vegetales", hint: "Vegetables"},
    { word: "el pollo", hint: "Chicken" },
    { word: "la fruta", hint: "Fruit" },
    { word: "el agua", hint: "Agua" },
    { word: "el queso", hint: "Cheese" },
    { word: "la carne", hint: "Meat" },
    { word: "la ensalada", hint: "Salad" }
];
