let spanish1UnitJWordList = [
    { word: "el abrigo", hint: "coat" },
    { word: "las botas", hint: "boots" },
    { word: "los calcetines", hint: "socks" },
    { word: "la camisa", hint: "shirt" },
    { word: "la camiseta", hint: "t-shirt" },
    { word: "la chaqueta", hint: "jacket" },
    { word: "la falda", hint: "skirt" },
    { word: "la gorra", hint: "baseball cap" },
    { word: "los guantes", hint: "gloves" },
    { word: "los jeans", hint: "jeans" },
    { word: "los pantalones", hint: "pants" },
    { word: "los cortos", hint: "shorts" },
    { word: "las chanclas", hint: "flip-flops / slides" },
    { word: "el sombrero", hint: "fancy hat" },
    { word: "la sudadera", hint: "sweatshirt" },
    { word: "el suéter", hint: "sweater" },
    { word: "los tenis", hint: "tennis shoes" },
    { word: "el traje", hint: "suit" },
    { word: "el traje de baño", hint: "swimsuit" },
    { word: "los zapatos", hint: "shoes" },
    { word: "el vestido", hint: "dress" },
    { word: "el gorro", hint: "knit stocking cap / tuque" },
    { word: "la bufanda", hint: "scarf" },
    { word: "amarillo", hint: "yellow" },
    { word: "rojo", hint: "red" },
    { word: "verde", hint: "green" },
    { word: "azul", hint: "blue" },
    { word: "negro", hint: "black" },
    { word: "blanco", hint: "white" },
    { word: "anaranjado", hint: "orange" },
    { word: "violeta", hint: "purple" },
    { word: "rosa", hint: "pink" },
    { word: "café", hint: "brown" },
    { word: "gris", hint: "gray" },
    { word: "llevo", hint: "I wear" },
    { word: "llevas", hint: "you wear" },
    { word: "ella lleva", hint: "she wears" },
    { word: "él lleva", hint: "he wears" },
    { word: "los calzoncillos", hint: "underwear" },
    { word: "el corpiño", hint: "bra" },
    { word: "las mallas", hint: "leggings" },
    { word: "las sandalias", hint: "sandals" },
    { word: "celeste", hint: "light blue" },
    { word: "turquesa", hint: "turquoise" },
    { word: "fucsia", hint: "fuchsia" },
    { word: "me pongo", hint: "I put on..." },
    { word: "te pones", hint: "You put on..." },
    { word: "¿qué me pongo?", hint: "What do I put on?" },
    { word: "¿cuándo llevas?", hint: "When do you wear?" },
    { word: "se pone", hint: "He/she puts on" },
    { word: "tengo frío", hint: "I'm cold" },
    { word: "¿qué te pones?", hint: "What do you put on?" },
    { word: "¿cuándo se pone?", hint: "When does he/she wear?" },
    { word: "está de moda.", hint: "It is fashionable" },
    { word: "tengo calor", hint: "I'm hot" },
    { word: "me queda mal", hint: "It fits me poorly" },
    { word: "me queda bien", hint: "It fits me well" },
    { word: "me queda grande", hint: "It's too big on me" },
    { word: "me queda pequeño", hint: "It's too small on me" },
    { word: "¿cómo le quedan?", hint: "How does it fit him/her? (shoes)" },
    { word: "te queda bien", hint: "It fits you well" },
    { word: "el estilo", hint: "The style" },
    { word: "¿cuánto cuesta?", hint: "How much does it cost?" },
    { word: "quiero comprar", hint: "I want to buy..." },
    { word: "necesito comprar", hint: "I need to buy..." },
    { word: "cuesta", hint: "It costs" },
    { word: "es caro", hint: "It is expensive" },
    { word: "es barato", hint: "It is cheap" },
    { word: "el centro comercial", hint: "The mall" },
    { word: "la tienda", hint: "The store" },
    { word: "el kiosko", hint: "The kiosk" },
    { word: "el dinero", hint: "The money" },
    { word: "el dólar", hint: "The dollar" },
    { word: "el peso", hint: "The peso" },
    { word: "el euro", hint: "The euro" },
    { word: "el precio", hint: "The price" },
    { word: "las rebajas", hint: "The sales" },
    { word: "quiero", hint: "I want" },
    { word: "quieres", hint: "You want" },
    { word: "quiere", hint: "He/she wants" },
    { word: "queremos", hint: "We want" },
    { word: "quieren", hint: "They want" },
    { word: "empiezo", hint: "I started" },
    { word: "empiezas", hint: "You started" },
    { word: "empieza", hint: "He/she started" },
    { word: "empezamos", hint: "We started" },
    { word: "empiezan", hint: "They started" },
    { word: "pienso", hint: "I think" },
    { word: "piensas", hint: "You think" },
    { word: "piensa", hint: "He/she thinks" },
    { word: "pensamos", hint: "We think" },
    { word: "piensan", hint: "They think" },
  ];
  