const spanish1UnitFWordList = [
        { word: "¿a qué hora es?", hint: "At what time is...?" },
        { word: "¿qué hora es?", hint: "What time is it?" },
        { word: "a la una", hint: "At one o'clock" },
        { word: "a las", hint: "At...o'clock" },
        { word: "es la una", hint: "It is one o'clock" },
        { word: "son las", hint: "It's... o'clock" },
        { word: "es la una de la tarde.", hint: "it's one in the afternoon" },
        { word: "son las once de la mañana.", hint: "It is eleven o'clock in the morning" },
        { word: "y cuarto", hint: "quarter after" },
        { word: "y media", hint: "thirty, half-past" },
        { word: "y doce", hint: ":12" },
        { word: "y treinta y cinco", hint: ":35" },
        { word: "fácil", hint: "easy" },
        { word: "difícil", hint: "difficult" },
        { word: "aburrido", hint: "boring" },
        { word: "estricto", hint: "strict" },
        { word: "divertido", hint: "fun" },
        { word: "interesante", hint: "interesting" },
        { word: "estresante", hint: "stressful" },
        { word: "tranquilo", hint: "calm" },
        { word: "loco", hint: "crazy" },
        { word: "la educación física", hint: "physical education" },
        { word: "la historia", hint: "history" },
        { word: "el inglés", hint: "English" },
        { word: "el arte", hint: "art" },
        { word: "las matemáticas", hint: "math" },
        { word: "el almuerzo", hint: "lunch" },
        { word: "la práctica", hint: "practice" },
        { word: "las ciencias", hint: "science" },
        { word: "el español", hint: "spanish" },
        { word: "empieza", hint: "begins" },
        { word: "termina", hint: "ends" },
        { word: "necesita", hint: "he/she needs" },
        { word: "necesito", hint: "I need" },
        { word: "la clase", hint: "class" },
        { word: "la clase de", hint: "the class of" },
        { word: "¿dónde está?", hint: "Where is...?" },
        { word: "el baño", hint: "bathroom" },
        { word: "la biblioteca", hint: "library" },
        { word: "la oficina del director", hint: "principal's office" },
        { word: "la oficina de la enfermera", hint: "nurse's office" },
        { word: "la oficina", hint: "office" },
        { word: "el salón de clases", hint: "classroom" },
        { word: "la oficina de consejera", hint: "counselor's office" },
        { word: "está cerca de", hint: "it's close to" },
        { word: "la cafetería", hint: "cafeteria" },
        { word: "está lejos de", hint: "It's far from" },
        { word: "el gimnasio", hint: "gym" },
        { word: "la escuela", hint: "school" },
        { word: "mis clases son", hint: "my classes are..." },
        { word: "mi clase de inglés es", hint: "My English class is..." },
        { word: "periodo uno", hint: "first period" },
        { word: "periodo dos", hint: "second period" }
    ];