const spanish1UnitEWordList = [
    { word: "el perro", hint: "dog" },
    { word: "el gato", hint: "cat" },
    { word: "comer", hint: "to eat" },
    { word: "saltar", hint: "to jump" },
    { word: "correr", hint: "to run" },
    { word: "caminar", hint: "to walk" },
    { word: "la fruta", hint: "fruit" },
    { word: "las verduras", hint: "vegetables" },
    { word: "la carne", hint: "meat" },
    { word: "el agua", hint: "water" },
    { word: "hace frío", hint: "it is cold" },
    { word: "hace calor", hint: "it is hot" },
    { word: "llueve", hint: "It is raining or it rains" },
    { word: "nieva", hint: "It is snowing or it snows" },
    { word: "grande", hint: "big" },
    { word: "pequeño", hint: "small" },
    { word: "alto", hint: "tall" },
    { word: "bajo", hint: "short" },
    { word: "gordo", hint: "overweight" },
    { word: "flaco", hint: "thin" },
    { word: "feo", hint: "ugly" },
    { word: "bonito", hint: "pretty" },
    { word: "los colores", hint: "colors" },
    { word: "rojo", hint: "red" },
    { word: "azul", hint: "blue" },
    { word: "verde", hint: "green" },
    { word: "amarillo", hint: "yellow" },
    { word: "naranja", hint: "orange" },
    { word: "anaranjado", hint: "orange" },
    { word: "blanco", hint: "white" },
    { word: "negro", hint: "black" },
    { word: "gris", hint: "gray" },
    { word: "morado", hint: "purple" },
    { word: "brown", hint: "café" },
    { word: "brown", hint: "marrón" },
    { word: "rosado", hint: "pink" },
    { word: "el otoño", hint: "autumn" },
    { word: "el verano", hint: "summer" },
    { word: "el invierno", hint: "winter" },
    { word: "la primavera", hint: "spring" },
    { word: "los meses del año", hint: "the months of the year" },
    { word: "enero", hint: "January" },
    { word: "febrero", hint: "February" },
    { word: "marzo", hint: "March" },
    { word: "abril", hint: "April" },
    { word: "mayo", hint: "May" },
    { word: "junio", hint: "June" },
    { word: "julio", hint: "July" },
    { word: "agosto", hint: "August" },
    { word: "septiembre", hint: "September" },
    { word: "octubre", hint: "October" },
    { word: "noviembre", hint: "November" },
    { word: "diciembre", hint: "December" },
    { word: "el lunes", hint: "Monday" },
    { word: "el martes", hint: "Tuesday" },
    { word: "el miércoles", hint: "Wednesday" },
    { word: "el jueves", hint: "Thursday" },
    { word: "el viernes", hint: "Friday" },
    { word: "el sábado", hint: "Saturday" },
    { word: "el domingo", hint: "Sunday" },
    { word: "los días de la semana", hint: "the days of the week" },
    { word: "los animales", hint: "animals" },
    { word: "el pájaro (el ave)", hint: "bird" },
    { word: "el hámster", hint: "hamster" },
    { word: "el pez", hint: "fish" },
    { word: "la serpiente", hint: "snake" },
    { word: "la iguana", hint: "iguana" },
    { word: "la rana", hint: "frog" },
    { word: "el cocodrilo", hint: "crocodile" },
    { word: "el caballo", hint: "horse" },
    { word: "el león", hint: "lion" },
    { word: "el tigre", hint: "tiger" },
    { word: "la jirafa", hint: "giraffe" },
    { word: "el pingüino", hint: "penguin" },
    { word: "la llama", hint: "llama" },
    { word: "el elefante", hint: "elephant" },
    { word: "el tiburón", hint: "shark" },
    { word: "la rata", hint: "rat" },
    { word: "el ratón", hint: "mouse" },
    { word: "el mono", hint: "monkey" },
    { word: "la tortuga", hint: "turtle" },
    { word: "el puma", hint: "puma" },
    { word: "el jaguar", hint: "jaguar" },
    { word: "el loro", hint: "parrot" },
    { word: "el capibara", hint: "capybara" },
    { word: "¿dónde viven los animales?", hint: "where do animals live?" },
    { word: "vive", hint: "she lives" },
    { word: "viven", hint: "they live" },
    { word: "el mar", hint: "the sea" },
    { word: "el océano", hint: "the ocean" },
    { word: "la costa", hint: "the coast" },
    { word: "la playa", hint: "the beach" },
    { word: "el lago", hint: "the lake" },
    { word: "el río", hint: "the river" },
    { word: "la selva", hint: "the jungle" },
    { word: "el desierto", hint: "the desert" },
    { word: "la montaña", hint: "the mountain" },
    { word: "el campo", hint: "the country" },
    { word: "el árbol", hint: "the tree" },
    { word: "la planta", hint: "the plant" },
    { word: "la cueva", hint: "the cave" },
    { word: "la isla", hint: "the island" },
    { word: "el volcán", hint: "the volcano" },
    { word: "¿cómo se llama...?", hint: "what is his or her name?" },
    { word: "¿cuál es su número de teléfono?", hint: "what is his or her phone number?" },
    { word: "¿de dónde es?", hint: "where is he or she from?" },
    { word: "¿cuándo es su cumpleaños?", hint: "when is his or her birthday?" },
    { word: "le gusta", hint: "he or she likes..." },
    { word: "no le gusta", hint: "he or she doesn't like..." },
    { word: "¿qué tiempo hace?", hint: "what is the weather like?" },
    { word: "¿cuántos años tiene?", hint: "how old is he or she?" },
    { word: "el cuerpo", hint: "body" },
    { word: "la cabeza", hint: "head" },
    { word: "los ojos", hint: "eyes" },
    { word: "la nariz", hint: "nose" },
    { word: "la boca", hint: "mouth" },
    { word: "los dientes", hint: "teeth" },
    { word: "las orejas", hint: "ears" },
    { word: "las piernas", hint: "legs" },
    { word: "las patas", hint: "paws" },
    { word: "la cola", hint: "tail" },
    { word: "las alas", hint: "wings" },
    { word: "el pelo", hint: "hair" },
    { word: "las manchas", hint: "spots" },
    { word: "las rayas", hint: "stripes" },
    { word: "curioso", hint: "curious" },
    { word: "ruidoso", hint: "noisy" },
    { word: "callado", hint: "quiet" },
    { word: "feroz", hint: "fierce" },
    { word: "cruel", hint: "cruel" },
    { word: "amable", hint: "kind" },
    { word: "puedo", hint: "I can" },
    { word: "puedes", hint: "you can" },
    { word: "puede", hint: "he or she can" },
    { word: "pueden", hint: "they can" },
    { word: "podemos", hint: "we can" },
    { word: "puede volar", hint: "he or she can fly" },
    { word: "vuela", hint: "he or she flies" },
    { word: "puede trepar", hint: "he or she can climb" },
    { word: "trepa", hint: "he or she climbs" },
    { word: "puede nadar", hint: "he or she can swim" },
    { word: "nada", hint: "he or she swims" },
    { word: "puede cantar", hint: "he or she can sing" },
    { word: "canta", hint: "he or she sings" },
    { word: "puede correr", hint: "he or she can run" },
    { word: "corre", hint: "he or she runs" },
    { word: "puede escuchar", hint: "he or she can listen" },
    { word: "escucha", hint: "he or she listens" },
    { word: "puede morder", hint: "he or she can bite" },
    { word: "muerde", hint: "he or she bites"}, 
    { word: "puede escapar", hint: "he or she can escape"},
    { word: "escapa", hint: "he or she escapes"},
    { word: "puede atacar", hint: "he or she can attack"},
    { word: "ataca", hint: "he or she attacks"},
    { word: "puede destruir", hint: "he or she can destroy"},
    { word: "destruye", hint: "he or she destroys"},
    { word: "puede hablar", hint: "he or she can talk"},
    { word: "habla", hint: "he or she talks"},
]
