const spanish1UnitCWordList = [
    { word: "tiene veinte años", hint: "He's twenty years old" },
    { word: "tengo quince años", hint: "I'm fifteen years old" },
    { word: "pequeño", hint: "small" },
    { word: "simpática", hint: "nice" },
    { word: "antipático", hint: "mean" },
    { word: "amable", hint: "kind" },
    { word: "cómico", hint: "funny" },
    { word: "atractivo", hint: "attractive" },
    { word: "bonita", hint: "pretty" },
    { word: "guapo", hint: "handsome/good looking" },
    { word: "divertido", hint: "fun" },
    { word: "trabajador", hint: "hard working" },
    { word: "cariñoso", hint: "affectionate" },
    { word: "mayor", hint: "older" },
    { word: "menor", hint: "younger" },
    { word: "sociable", hint: "outgoing" },
    { word: "tímido", hint: "shy" },
    { word: "pequeño", hint: "small" },
    { word: "grande", hint: "big" },
    { word: "feo", hint: "ugly" },
    { word: "bonito", hint: "pretty" },
    { word: "alto", hint: "tall" },
    { word: "bajo", hint: "short" },
    { word: "gordo", hint: "fat" },
    { word: "flaco", hint: "skinny" },
    { word: "joven", hint: "young" },
    { word: "viejo", hint: "old" },
    { word: "el pelo rubio", hint: "blond hair" },
    { word: "el pelo negro", hint: "black hair" },
    { word: "el pelo rojo", hint: "red hair" },
    { word: "el pelo castaño", hint: "brown hair" },
    { word: "el pelo gris", hint: "gray hair" },
    { word: "los ojos azules", hint: "blue eyes" },
    { word: "los ojos verdes", hint: "green eyes" },
    { word: "los ojos negros", hint: "black eyes" },
    { word: "los ojos cafés", hint: "brown eyes" },
    { word: "el bigote", hint: "mustache" },
    { word: "la barba", hint: "beard" },
    { word: "los lentes", hint: "glasses" },
    { word: "el gorro", hint: "hat" },
    { word: "los audífonos", hint: "headphones" },
    { word: "el pelo corto", hint: "short hair" },
    { word: "el pelo largo", hint: "long hair" },
    { word: "soy", hint: "I am" },
    { word: "eres", hint: "you are" },
    { word: "es", hint: "he/she is" },
    { word: "tengo", hint: "I have" },
    { word: "no tengo", hint: "I don't have" },
    { word: "tienes", hint: "you have" },
    { word: "no tienes", hint: "you don't have" },
    { word: "tiene", hint: "she/he has" },
    { word: "no tiene", hint: "she/he doesn't have" },
    { word: "el chico", hint: "boy" },
    { word: "la chica", hint: "girl" },
    { word: "la mujer", hint: "woman" },
    { word: "el hombre", hint: "man" },
    { word: "el niño", hint: "boy child" },
    { word: "la niña", hint: "girl child" },
    { word: "profesor", hint: "professor (man)" },
    { word: "profesora", hint: "professor (woman)"},
    { word: "maestro", hint: "teacher (man)"},
    { word: "maestra", hint: "teacher (woman)"},
    { word: "director", hint: "principal (man)" },
    { word: "directora", hint: "principal (woman)" },
    { word: "maestra", hint: "teacher" },
    { word: "secretaria", hint: "secretary" },
    { word: "policía", hint: "police officer" },
    { word: "guardia", hint: "guardian" },
    { word: "detective", hint: "detective" },
    { word: "el amigo", hint: "male friend" },
    { word: "la amiga", hint: "female friend" },
    { word: "el novio", hint: "boyfriend" },
    { word: "la novia", hint: "girlfriend" },
    { word: "el", hint: "the(masculine)" },
    { word: "la", hint: "the(feminine)" },
    { word: "un", hint: "a/an (masculine)" },
    { word: "una", hint: "a, an (feminine)" },
    { word: "trabajador", hint: "hard worker (man)" },
    { word: "trabajadora", hint: "hard worker (woman)"}
]