const spanishNumbersBig = [
    { word: "trescientos", hint: "three hundred" },
    { word: "cuatrocientos", hint: "four hundred" },
    { word: "quinientos", hint: "five hundred" },
    { word: "seiscientos", hint: "six hundred" },
    { word: "setecientos", hint: "seven hundred" },
    { word: "ochocientos", hint: "eight hundred" },
    { word: "novecientos", hint: "nine hundred" },
    { word: "mil", hint: "one thousand" },
    { word: "dos mil", hint: "two thousand" },
    { word: "tres mil", hint: "three thousand" },
    { word: "cuatrocientos veinticinco", hint: "425" },
    { word: "cuatro mil doscientos treinta y ocho", hint: "4,238" },
    { word: "diez mil", hint: "10,000" },
    { word: "cuarenta mil setecientos cincuenta y nueve", hint: "40,759" },
    { word: "siete mil seiscientos noventa y cuatro", hint: "7,694" },
    { word: "doscientos cuarenta y cinco mil novecientos setenta y tres", hint: "245,973" },
    { word: "sesenta y ocho mil quinientos doce", hint: "68,512" },
    { word: "tres millones ochocientos setenta y cuatro mil trescientos noventa y uno", hint: "3,874,391" },
    { word: "dos millones", hint: "2,000,000" },
    { word: "trece mil cincuenta", hint: "13,050" },
    { word: "setecientos veinte", hint: "720" },
    { word: "trescientos noventa y seis mil doscientos cinco", hint: "396,205" },
    { word: "doscientos", hint: "two hundred" },
    { word: "cien/ ciento", hint: "one hundred" },
    { word: "veinte", hint: "twenty" },
    { word: "treinta", hint: "thirty" },
    { word: "cuarenta", hint: "forty" },
    { word: "cincuenta", hint: "fifty" },
    { word: "sesenta", hint: "sixty" },
    { word: "setenta", hint: "seventy" },
    { word: "ochenta", hint: "eighty" },
    { word: "noventa", hint: "ninety" },
    { word: "ciento ocho", hint: "108" },
    { word: "novecientos setenta y uno", hint: "971" },
    { word: "quinientos diecisiete", hint: "517" },
    { word: "mil millones", hint: "1,000,000,000" },
    { word: "diez mil millones", hint: "10,000,000,000" },
    { word: "quinientos mil millones", hint: "500,000,000,000" },
    { word: "dos mil veinticuatro", hint: "2024" },
    { word: "setecientos mil doscientos trece", hint: "700,213" }
];
