const spanish1UnitHWordList = [
    { word: "la comida", hint: "the food, meal" },
    { word: "el desayuno", hint: "the breakfast" },
    { word: "el almuerzo", hint: "the lunch" },
    { word: "la cena", hint: "the dinner, supper" },
    { word: "la carne", hint: "the meat" },
    { word: "el jamón", hint: "the ham" },
    { word: "el tocino", hint: "the bacon" },
    { word: "el bistec", hint: "the beef steak" },
    { word: "el pollo", hint: "the chicken" },
    { word: "la sopa", hint: "the soup" },
    { word: "el pescado", hint: "the fish" },
    { word: "los mariscos", hint: "the seafood" },
    { word: "los camarónes", hint: "shrimp" },
    { word: "la langosta", hint: "lobster" },
    { word: "el yogur", hint: "the yogurt" },
    { word: "el queso", hint: "the cheese" },
    { word: "los huevos", hint: "the eggs" },
    { word: "la tortilla de huevo", hint: "the omelet" },
    { word: "el sandwich/el bocadillo", hint: "the sandwich" },
    { word: "el pan", hint: "the bread" },
    { word: "la mantequilla", hint: "the butter" },
    { word: "el arroz", hint: "the rice" },
    { word: "las verduras/los vegetales", hint: "the vegetables" },
    { word: "los guisantes", hint: "the peas" },
    { word: "el maíz", hint: "the corn" },
    { word: "los tomates", hint: "the tomatoes" },
    { word: "las zanahorias", hint: "the carrots" },
    { word: "las judías verdes", hint: "the green beans" },
    { word: "la cebolla", hint: "the onion" },
    { word: "la ensalada", hint: "the salad" },
    { word: "la lechuga", hint: "the lettuce" },
    { word: "las papas", hint: "the potatoes" },
    { word: "las papas fritas", hint: "the French fries" },
    { word: "el azúcar", hint: "the sugar" },
    { word: "la sal", hint: "the salt" },
    { word: "la pimienta", hint: "the pepper" },
    { word: "la mayonesa", hint: "the mayonnaise" },
    { word: "el aceite", hint: "the oil" },
    { word: "los frijoles/las habichuelas", hint: "the beans" },
    { word: "las frutas", hint: "the fruits" },
    { word: "la naranja", hint: "the orange" },
    { word: "el plátano/el guineo", hint: "the banana" },
    { word: "la manzana", hint: "apple" },
    { word: "la pera", hint: "pear" },
    { word: "el melocotón", hint: "peach" },
    { word: "la fresa", hint: "strawberry" },
    { word: "la cereza", hint: "cherry" },
    { word: "la sandía", hint: "the watermelon" },
    { word: "las uvas", hint: "the grapes" },
    { word: "la piña", hint: "the pineapple" },
    { word: "el aguacate", hint: "the avocado" },
    { word: "la papaya", hint: "the papaya" },
    { word: "el mango", hint: "the mango" },
    { word: "la mermelada", hint: "the jam" },
    { word: "la mantequilla de maní", hint: "the peanut butter" },
    { word: "los dulces", hint: "the candies" },
    { word: "los postres", hint: "the desserts" },
    { word: "el pastel", hint: "the cake" },
    { word: "la tarta", hint: "the pie" },
    { word: "el helado", hint: "the ice cream" },
    { word: "la leche", hint: "the milk" },
    { word: "jugo de naranja", hint: "orange juice" },
    { word: "un café", hint: "a coffee" },
    { word: "un té", hint: "a tea" },
    { word: "un té helado", hint: "an ice tea" },
    { word: "una limonada", hint: "a lemonade" },
    { word: "un chocolate caliente", hint: "a hot chocolate" },
    { word: "un refresco", hint: "a refreshment" },
    { word: "las bebidas", hint: "the drinks" },
    { word: "la cuenta, por favor.", hint: "Could I have the bill, please." },
    { word: "el menú", hint: "the menu" },
    { word: "servilleta", hint: "napkin" },
    { word: "el tenedor", hint: "the fork" },
    { word: "el cuchillo", hint: "the knife" },
    { word: "la cuchara", hint: "the spoon" },
    { word: "el plato", hint: "the plate" },
    { word: "los cubiertos", hint: "the silverware" },
    { word: "el vaso", hint: "the glass" },
    { word: "la taza de café", hint: "the coffee cup" },
    { word: "la estufa", hint: "the stove" },
    { word: "espárrago", hint: "asparagus" },
    { word: "pepino", hint: "cucumber" },
    { word: "tengo hambre", hint: "I am hungry" },
    { word: "tengo sed", hint: "I am thirsty" },
    { word: "estoy lleno/a", hint: "I am full" },
    { word: "la miel", hint: "the honey" },
    { word: "el sabor", hint: "taste, flavor" },
    { word: "saber a", hint: "to taste like" },
    { word: "agrio", hint: "sour" }, 
    { word: "salado", hint: "salty"},
    { word: "picante", hint: "spicy"},
];